### ISSUE TITLE
init() missing 1 required positional argument: 'option'

### ISSUE THREAD

**Issue by HAlover99** [jomwells/ambilight-yeelight#10]
dear jomwells,

could you help me?
i configured the platform under switch section in configuration file.

Logger: homeassistant.components.hassio
Source: components/hassio/__init__.py:588
Integration: Home Assistant Supervisor (documentation, issues)
First occurred: 17:26:55 (1 occurrences)
Last logged: 17:26:55

The system cannot restart because the configuration is not valid: Platform error switch.philips_ambilight+yeelight - Integration 'philips_ambilight+yeelight' not found.

**Comment by HAlover99** [comment]
i added the version on manifest.json file and HA tried to load the plugin but unfortunatel it generate the follow error:

Logger: homeassistant.components.switch
Source: custom_components/philips_ambilight+yeelight/switch.py:40
Integration: Interruttore (documentation, issues)
First occurred: 10:24:47 (1 occurrences)
Last logged: 10:24:47

Error while setting up philips_ambilight+yeelight platform for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/philips_ambilight+yeelight/switch.py", line 40, in setup_platform
    add_devices([AmbiHue(name, tvip, bulbip, user, password, option)])
TypeError: __init__() missing 1 required positional argument: 'option'

**Comment by bosser2407** [comment]
Same problem
